#! /usr/bin/env bash

declare CLAY_HOME
CLAY_HOME="$( cd "$( dirname "$0" )" >/dev/null && pwd )"

source "$CLAY_HOME/cli/up.sh"
source "$CLAY_HOME/cli/run.sh"
source "$CLAY_HOME/cli/down.sh"

declare -A commands
commands=(
    [up]=up
    [run]=run
    [down]=down
)

# get command to execute
command=$1
shift

# Run desired command and pass any given parameters
${commands[$command]} "$@"
